config/routes.rb
Rails.application.routes.draw do

  resources :books

  resources :books do
    resources :reviews
  end

  resources :authors do
    resources :authors
  end

  root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_uniqueness_of :first_name, scope: :last_name
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :category
  accepts_nested_attributes_for :author

  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :year, presence: true
  validates :year, length: { is: 4 }
  validates_uniqueness_of :title, scope: :author_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books

  validates :name, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book

  validates :rating, presence: true
  validates :rating, inclusion: { in: 1..5 }
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.limit(50)
  end

  def show
    @book = Book.find(params[:id])
    @review = Review.new
    @reviews = @book.reviews
  end

  def new
    @book = Book.new
    @book.author = Author.new
  end

  def create
    @book = Book.new(book_params)

    if new_author = Author.find_by(first_name: @book.author.first_name, last_name: @book.author.last_name)
      @book.author = new_author
      @notice = 'Book successfully created with existing author.'
    else
      @notice = 'Book successfully created with new author.'
    end

    if @book.save
      redirect_to @book, notice: @notice
    else
      render :new, notice: "Your book and/or author couldn't be saved."
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :year, :description, :category_id,
      author_attributes: [ :first_name, :last_name ] )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def create
    @book = Book.find(params[:book_id])

    @review = Review.new(review_params)

    @review.book = @book

    if @review.save
      redirect_to book_path(@book), notice: 'Review successfully created.'
    else
      render 'books/show'
    end
  end

  def review_params
    params.require(:review).permit(:body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<h2>Books</h2>

<% @books.each do |book| %>

  <div class="book">
    <h3>
      <h3><%= link_to book.title, book_path(book) %></h3>
    <p><%= book.description %></p>
  </div>

<% end %>

app/views/books/new.html.erb
<h2>Add Book</h2>

<section>
  <%= simple_form_for @book do |f| %>

    <%= f.input :title %>

    <%= f.simple_fields_for :author do |author_form| %>

    <fieldset>

      <legend>Author:</legend>

      <%= author_form.input :first_name %>

      <%= author_form.input :last_name %>
    </fieldset>
    <% end %>

    <%= f.input :year %>

    <%= f.input :description %>

    <%= f.association :category %>

    <%= f.button :submit %>

  <% end %>
</section>

app/views/books/show.html.erb
<section class="details">
  <h2>Book Details</h2>

  <ul>
    <li><strong>Title:</strong> <%= @book.title %>
    <li><strong>Author:</strong> <%= @book.author.first_name %> <%= @book.author.last_name %></li>
    <li><strong>Category:</strong> <%= @book.category.name %></li>
    <li><strong>Year Published:</strong> <%= @book.year %></li>
    <li><strong>Description:</strong> <%= @book.description %></li>
  </ul>

  <h3>Reviews</h3>
  <hr>

  <% @book.reviews.each do |review| %>
    <div class="review">
      <strong>Rating:</strong> <%= review.rating %>
      <p><%= review.body %></p>
    </div>
  <% end %>

</section>

<section class="add-review">

  <h4>Create Review</h4>
  <hr>

    <%= simple_form_for [@book, @review] do |f| %>

      <%= f.input :rating, collection: 1..5 %>
      <%= f.input :body %>

      <%= f.button :submit %>

    <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <link href='http://fonts.googleapis.com/css?family=Lusitana:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather+Sans:400,300,300italic,400italic,700italic,700,800,800italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">

      <header>
        <h1><a href="/">Book Club</a></h1>

        <div class="button-group">
          <button><%= link_to "Books", books_path %></button>
          <button><%= link_to "Add Book", new_book_path %></button>
        </div>

        <div class="notice">
          <%= flash[:notice] %>
        </div>

        <div class="alert">
          <%= flash[:alert] %>
        </div>
      </header>

      <article>
        <%= yield %>
      </article>

    </div>

  </body>
</html>